name: Github Actions CI
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: cv.tex
    - name: Check pdf file
      run: |
        file cv.pdf | grep -q ' PDF '


    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'cv.pdf'
        destination_repo: 'kelseygonzalez/website'
        destination_folder: 'static/files'
        user_email: 'kelseygonzalez@email.arizona.edu'
        user_name: 'kelseygonzalez'

      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
